// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtppslwojvwfawtodlaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0cHBzbHdvanZ3ZmF3dG9kbGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjcxNDksImV4cCI6MjA1OTAwMzE0OX0.HG44F-95M6dUlzof7odAJBE20SEM9kpOTKbpDCuc7zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);